### ISSUE TITLE
Correct placement of message "There are no products matching the selection"

### ISSUE THREAD

**Issue by Vinai** [lizards-and-pumpkins/sample-project#15]
While the initial import is still running, any category or search page will display the message `There are no products matching the selection`.

<img width="658" alt="bildschirmfoto 2016-11-28 um 11 31 00" src="https://cloud.githubusercontent.com/assets/72463/20665036/3617bcea-b55e-11e6-9e4b-6767a572c125.png">

Because there is no margin between the text and the left side of the browser window it looks a bit broken. It would be great if the text could be centered or at least be separated by some small amount.

The code can be found in the file
`src/magento-themes/magento-sample-theme/app/design/frontend/lizardsandpumpkins/default/template/catalog/product/list.phtml`

```html
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
```

**Comment by tim-bezhashvyly** [comment]
I like "Ponies!" bookmark. 😊
