### ISSUE TITLE
Tests failing because of strange country map en => DE

### ISSUE THREAD

**Issue by nhp** [lizards-and-pumpkins/sample-project#4]
There is one failing test because of something that looks like a typo or copy'n'paste Error. 
I would expect ```'en' => 'EN' ``` instead of ```'en' => 'DE' ```.

**Comment by tim-bezhashvyly** [comment]
Thanks. Fixed.

**Comment by nhp** [comment]
Ouch. Just in the time i needed to fork and pr it myself. Super fast Tim :)
