### ISSUE TITLE
Support both dot and comma as decimal separator

### ISSUE THREAD

**Issue by tim-bezhashvyly** [lizards-and-pumpkins/sample-project#57]
As backend returns different price format for different locales (5,55 for de_DE and 5.55 for en_US) javascript which parses the price for filter navigation must support both.

**Comment by Vinai** [comment]
Why do we need this? Can you add a description of the issue? I don't get it just based on the code change.

**Comment by tim-bezhashvyly** [comment]
Description is updated.

**Comment by Vinai** [comment]
Thanks you. I'm happy to merge, but many locales (including de_DE, en_US and en_GB) specify a `.` or `,` as the thousands separator. If this code is for parsing the locale representations of numbers then those need to be respected, too.
