### ISSUE TITLE
send command/event consumer process to the background in supervisor script

### ISSUE THREAD

**Issue by mookie-** [lizards-and-pumpkins/sample-project#65]
If you send the consumer script to the background in the supervisor script and do the loop like:

```
if command_still_running
  sleep $interval
else
  exit_code_check
  start_new_consumer
fi
```

Then you could also add the send_shutdown_message there and don't depend on the manage_workers.sh. The manage_workers.sh is only usable interactive. The consumerSupervisor.sh can be used in init script and/or something like monit to monitor and automate the start/stop/restart.

**Comment by Vinai** [comment]
Thanks for reporting the issue!
I considered adding that logic to the supervisor script, but I want to keep it agnostic to what command it is running. For example, it is also used by the export queue poll script of the Magento connector.

What I want to do is I want to extract a new command to start and stop consumers specifically, that then will also contain the logic to send the shutdown message.
This in turn can then be used by the `manage_workers.sh` script.

Currently the process hierarchy looks like this:

```
- manage_workers.sh
  - commandSupervisor.sh
    - commandConsumer.php
```

With the new command, the process hierarchy will be:

```
- manage_workers.sh
  - manageConsumer.sh <- the new command
    - commandSupervisor.sh
      - commandConsumer.php
```

Starting and stopping command and event queue consumers in a script can then be accomplished with the manageConsumer.sh command, passing the type of consumer (`command` or `event`) and the desired action (`start` or `stop`) as arguments.

For example:

```
$ manageConsumer.sh command start
$ manageConsumer.sh event stop
```

**Comment by mookie-** [comment]
Ok, thanks. Then you probably can close this issue. I just thought about it and wanted to tell you.

**Comment by Vinai** [comment]
I've extracted the script (see referenced PR above).
Usage:
`src/lizards-and-pumpkins/bin/manage-consumer.sh (event|command) (start|stop|stop-all)`

Still want to add a third parameter for `start` and `stop` to specify how many to start or stop, so lets leave this issue open.

**Comment by Vinai** [comment]
Added the numeric argument as noted above:

```
Usage:
src/lizards-and-pumpkins/bin/manage-consumer.sh (event|command) (start|stop) [count]
src/lizards-and-pumpkins/bin/manage-consumer.sh (event|command) stop-all
```
