### ISSUE TITLE
Search facets are not quite right

### ISSUE THREAD

**Issue by Vinai** [lizards-and-pumpkins/sample-project#82]
The facets are not right.  
For example http://demo.lizardsandpumpkins.com.loc/en/men/shirts.html  
The price ranges are wrong, and the display of selected filters doesn't seem to work.
The counts for the other options seem odd, too.

<img width="1001" alt="bildschirmfoto 2017-01-29 um 23 33 42" src="https://cloud.githubusercontent.com/assets/72463/22408576/a0cba5bc-e67b-11e6-9e16-41c43966a426.png">

Only 3 products are part of the listing.  
* Two of them are assigned to the 0-20 price range aggregation.  
* When the price filter is selected, all it does is it moves the filter to the top. No other indication is given that it's selected (the same is true for other filters).
* The size facets lists many more available products, even though the max should probably be 3.

I assume these actually might be bugs in the file system search engine. Because of the importance of the sample project and the dev vm, we should fix it or remove it. Lets fix it :)

**Comment by tim-bezhashvyly** [comment]
Should be resolved by https://github.com/lizards-and-pumpkins/catalog/pull/1002
